OUTPUT TO PRINTER.
PUT CONTROL CHR(27) + CHR(64) + CHR(80). /* 10 cpi*/  /* Modo Condensado*/
   PUT UNFORMATTED "10 CPI NORMAL" SKIP.
PUT CONTROL CHR(27) + CHR(15). /* 12 cpi*/
   PUT UNFORMATTED "10 CPI CONDENSADO" SKIP.
PUT CONTROL CHR(27) + CHR(18).
PUT CONTROL CHR(27) + CHR(77).
   PUT UNFORMATTED "12 CPI NORMAL" SKIP.
PUT CONTROL CHR(27) + CHR(15). 
   PUT UNFORMATTED "12 CPI CONDENSADO" SKIP.
