  FIELD Nit LIKE Creditos.Nit~
  FIELD Cod_Credito LIKE Creditos.Cod_Credito~
  FIELD Num_Credito LIKE Creditos.Num_Credito~
  FIELD Monto LIKE Creditos.Monto~
  FIELD Pagare LIKE Creditos.Pagare~
  FIELD Sdo_Capital LIKE Creditos.Sdo_Capital~
  FIELD Fec_Aprobacion LIKE Creditos.Fec_Aprobacion~
  FIELD Fec_Desembolso LIKE Creditos.Fec_Desembolso~
  FIELD Fec_UltPago LIKE Creditos.Fec_UltPago
