/*
databases= "bdcentral"
config= query
version= 2.1A
results.status-area= true 
results.toolbar= true 
results.summary= false
results.governor= 0
results.govergen= false
results.detail-level= 0
results.name= "ClientesActualizacion"
results.view-as= report
results.table[1]= "bdcentral.Clientes" "60653" "" "" no ""
results.field[1]= "bdcentral.Clientes.Nit" "Nit" "X(12)" "" "character" "" "1" ",,,,,"
results.field[2]= "bdcentral.Clientes.Nombre" "Nombre" "X(40)" "" "character" "" "1" ",,,,,"
results.field[3]= "bdcentral.Clientes.Apellido1" "Primer Apellido" "X(15)" "" "character" "" "1" ",,,,,"
results.field[4]= "bdcentral.Clientes.Apellido2" "Segundo Apellido" "X(15)" "" "character" "" "1" ",,,,,"
results.field[5]= "bdcentral.Clientes.Agencia" "Agencia" "999" "" "integer" "" "1" ",,,,,"
results.field[6]= "bdcentral.Clientes.Cod_Empresa" "Código Asignado a la Empresa" "9999" "" "integer" "" "1" ",,,,,"
results.field[7]= "bdcentral.Clientes.Tel_Residencia" "Teléfono de la Residencia" "X(20)" "" "character" "" "1" ",,,,,"
results.field[8]= "bdcentral.Clientes.Tel_comercial" "Tel Comercial" "X(20)" "" "character" "" "1" ",,,,,"
results.field[9]= "bdcentral.Clientes.Fec_UltActualiza" "Fecha Ultima Actualización" "99/99/9999" "" "date" "" "1" ",,,,,"
results.order[1]= "bdcentral.Clientes.Agencia" "ascending"
results.order[2]= "bdcentral.Clientes.Apellido1" "ascending"
export.type= PROGRESS
export.use-headings= no 
export.fixed-width= no 
export.prepass= no 
export.base-date= ?
export.record-start= ""
export.record-end= "32,13,10"
export.field-delimiter= "34"
export.field-separator= "32"
export.delimit-type= "*"
export.description= "PROGRESS Export"
label.type= "Default layout"
label.dimension= "3-1/2""x15/16"""
label.left-margin= 0
label.label-width= 35
label.total-height= 5
label.vert-space= 1
label.horz-space= 0
label.number-across= 1
label.number-copies= 1
label.omit-blank= true 
report.format= "Letter"
report.dimension= "8-1/2 x 11 in"
report.time= 
report.left-margin= 1
report.page-size= 60
report.page-width= 197
report.column-spacing= 1
report.line-spacing= 1
report.top-margin= 1
report.before-body= 1
report.after-body= 1
report.page-eject= "bdcentral.Clientes.Agencia"
*/

