DEFINE INPUT  PARAMETER pBio      AS INTEGER.
DEFINE INPUT  PARAMETER pTran     AS INTEGER.
DEFINE INPUT  PARAMETER pCC       AS CHARACTER.
DEFINE INPUT  PARAMETER pNroCta   AS CHARACTER.
DEFINE INPUT  PARAMETER pNroTar   AS CHARACTER.
DEFINE INPUT  PARAMETER pMonto          AS CHARACTER INITIAL '0000000000000'.
DEFINE INPUT-OUTPUT  PARAMETER pSec     AS CHARACTER INITIAL '0000000000000'.
DEFINE INPUT-OUTPUT  PARAMETER pSaldo   AS CHARACTER INITIAL '0000000000000'.
DEFINE INPUT-OUTPUT  PARAMETER pSalDis  AS CHARACTER INITIAL '0000000000000'.
DEFINE OUTPUT PARAMETER retCod AS INTEGER INITIAL -1.
pmonto = TRIM(STRING(pmonto)).
/*
RUN Enviar.
 */
PROCEDURE Enviar:    
    PAUSE 1.
    RUN WC_TranAcc(pBio, 
                   pTran, 
                   pCC, 
                   pNroCta, 
                   pNroTar,
                   pMonto, 
                   INPUT-OUTPUT pSec,
                   INPUT-OUTPUT pSaldo, 
                   INPUT-OUTPUT pSalDis,
                   OUTPUT retCod). 
    PAUSE 2.
END PROCEDURE.

PROCEDURE WC_TranAcc EXTERNAL "c:\webcaja.2006\WebCajaLib.dll" STDCALL:
    DEFINE INPUT  PARAMETER Bio      AS BYTE.
    DEFINE INPUT  PARAMETER Tran     AS BYTE.
    DEFINE INPUT  PARAMETER CC       AS CHARACTER.
    DEFINE INPUT  PARAMETER NroCta   AS CHARACTER.
    DEFINE INPUT  PARAMETER NroTar   AS CHARACTER.
    DEFINE INPUT  PARAMETER Monto    AS CHARACTER.
    DEFINE INPUT-OUTPUT  PARAMETER sec      AS CHARACTER.
    DEFINE INPUT-OUTPUT  PARAMETER Tot      AS CHARACTER.
    DEFINE INPUT-OUTPUT  PARAMETER Dis      AS CHARACTER.
    DEFINE RETURN PARAMETER retCod   AS BYTE.
END.
