DEFINE INPUT PARAMETER numDoc AS CHARACTER.
DEFINE INPUT PARAMETER tipoDoc AS CHARACTER.
DEFINE OUTPUT PARAMETER flag AS LOGICAL.

DEFINE VAR numDocInt AS INTEGER.

numDocInt = INTEGER(numDoc) NO-ERROR.

IF ERROR-STATUS:ERROR =  FALSE THEN DO:
    IF tipoDoc <> "NIT" AND numDocInt >= 600000000 AND numDocInt <= 999999999 THEN
        flag = TRUE.
    
    IF tipoDoc = "NIT" AND (numDocInt < 600000000 OR numDocInt > 999999999) THEN
        flag = TRUE.
END.
