DEFINE {1} VAR T_Nit AS CHARACTER FORMAT "X(12)".
DEFINE {1} VAR T_Per AS LOGICAL.
DEFINE {1} VAR W_Aso AS LOGICAL.
DEFINE {1} VAR T_Doc AS LOGICAL INITIAL FALSE.
DEFINE {1} VAR W_Tercero AS LOGICAL INITIAL FALSE.
DEFINE {1} VAR W_CIIU AS INTEGER FORMAT "9999".
